---
output: html_document
---

# - __Conclusão da Análise__

Observando os efeitos de intervenções, tanto por parte do governo com a obrigatoriedade para a população permanecer em casa e se direcionar ao sistema de saúde em casos de urgência/emergência ou suspeita de covid, assim como a interferência de um órgão regulador do setor da saúde suplementar, como foi o caso da suspensão de procedimentos presenciais emitido pela Agência Nacional de Saúde Suplementar, foi observado que no estado do Ceará, dividindo as despesas entre procedimentos ambulatoriais e hospitalares, o impacto de tais intervenções foi maior na parte ambulatorial. Tal efeito é lógico, já que maior parte da população realiza procedimentos na parte do ambulatório médico. Olhando a despesa Hospitalar, é possível constatar que esta sofreu menos impacto, oscilando em torno da média prevista pelo modelo utilizado. O menor valor observado para o ano de 2020 foi em Abril, sendo de R$ 68.507.917,00 de despesa. 
O modelo havia previsto para o mesmo mês o valor mínimo de R$ 66.280.859,00 e máximo de 
R$ 114.397.527,00; com média em
R$ 90.339.193,00. Para os procedimentos ambulatoriais o menor valor observado foi no mesmo mês (Abril de 2020) sendo igual a 
R$ 79.382.434,00; nesse grupo de procedimentos, os meses de Março a Setembro e o mês de Dezembro ficaram abaixo do mínimo projetado para os respectivos períodos.

Vale salientar que tais medidas de intervenção tiveram como intuito diminuir o fluxo de pessoas nos estabelecimentos de saúde visando mitigar a proliferação e infecção pela COVID-19.
